/*
|--------------------------------------------------------------
| OYO Website Task Runners
|--------------------------------------------------------------
| Please do not edit this file incase you dont know what
| you are doing
*/

'use strict';

module.exports = function(grunt) {
	grunt.initConfig({

		bowercopy : {
			scripts : {
				files : {
				'app/js/vendor/datepicker.js' : 'datepicker-fr/ui/datepicker.js',
				'app/scss/vendor/_datepicker.scss' : 'datepicker-fr/themes/base/datepicker.css'
					}
			}
		},

		sass : {
			dev : {
				options : {
					style : 'expanded',
					lineNumbers : true,
					cacheLocation : 'app/scss/.sass-cache',
					trace : true,
				},
				files : {
					'public/stylesheets/style.css' : 'app/scss/inbox.scss'
				}
			}
		},

    autoprefixer: {
	    prefix: {
	      options: {
	        browsers: ['last 2 versions', 'ie 8', 'ie 9']
	      },
	      src: 'public/stylesheets/style.css',
	      dest: 'public/stylesheets/style.css'
	    }
	  },

	  express: {
	    dev: {
	      options: {
	        script: 'server.js'
	      }
	    },
	  },

		browserify: {
			dev: {
				options: {
					browserifyOptions : {debug: true, }
				},
				src: ['app/js/modules/entry.js'],
				dest: 'public/bundle.js'
			}
		},

		imagemin: {
			dynamic: {
				option: {
					cache: false
				},
				files: [{
					expand: true,
					cwd: 'app/images/',
					src: '**/*.{png,jpg,gif}',
					dest: 'public/images/'
				}]
			}
		},

		watch: {
			options: {
				livereload: true,
			},
			styles: {
				files: ['app/scss/**/*.scss'],
				tasks: ['sass:dev'],
				options: {
					spawn: true,
				}
			},
			scripts: {
				files: ['app/js/**/*.js'],
				tasks: ['browserify'],
			},
			express: {
				files:  [ 'server.js' ],
				tasks: ['express:dev'],
				options: {
					spawn: false,
				}
			},
		}

});

	grunt.loadNpmTasks('grunt-contrib-imagemin');
	grunt.loadNpmTasks('grunt-express-server');
	grunt.loadNpmTasks('grunt-contrib-watch');
	grunt.loadNpmTasks('grunt-contrib-sass');
	grunt.loadNpmTasks('grunt-browserify');
	grunt.loadNpmTasks('grunt-bowercopy');
	grunt.registerTask('bower', ['bowercopy']);
	grunt.registerTask('dev', ['sass:dev',  'browserify:dev', 'imagemin', 'express', 'watch']);

};
